server:
  port: 8004

spring:
  application:
    name: gateway
  cloud:
      gateway:
        routes:
        - id: customer
          uri: http://localhost:8002/customer
          predicates:
          - Path=/customer/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

