server:
  port: 8005

spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

zuul:
  routes:
    customer:
      path: /customer/**
      url: http://localhost:8002/customer
    admin:
      path: /admin/**
      serviceId: client_server_admin
      stripPrefix: false

ribbon:
  eureka:
    enabled: true


client_server_admin:
  ribbon:
    listOfServers: http://localhost:8003/admin, http://localhost:8006/admin


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000